# Generated by Django 3.2.3 on 2021-05-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефону ')),
                ('email', models.CharField(max_length=30, verbose_name='Пошта')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнтів',
            },
        ),
    ]
